version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    target_branch: "master"
    default_labels:
    - "Type: Maintenance"
    - "Type: Security"
    - "Type: Environment"
    allowed_updates:
    - match:
        update_type: "security"
    automerged_updates:
    - match:
        dependency_type: "all"
        update_type: "all"
    version_requirement_updates: "auto"